import javax.swing.*;
import javax.xml.stream.events.StartDocument;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.Scanner;

public class View {
    private JButton val1;
    private JButton val2;
    private JPanel tabel;
    String password = "password";
    private JTextField textField;
    int currentRoom = 1;
    ArrayList<Integer> storyLinks = new ArrayList();

    public View() {
        JFrame frame = new JFrame("Main");
        frame.setContentPane(this.tabel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(600, 400);
        frame.setVisible(true);
        update();

        textField.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
            }
        });
        /**
         * Jag har skapat två click knappar som kommer vara alternativena för projektet
         */

        val1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
            // Sätt current room och gör update
                currentRoom = storyLinks.get(0);
                update();
            }


        });
        val2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                currentRoom = storyLinks.get(1);
                update();
            }
        });


    }

    private void update() {
        try {
            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/exempel? " +
                            "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
                    "solomon", password);
            Statement stmt = conn.createStatement();

            String SQLQuery = "select body from story where id = " + currentRoom;

            ResultSet rset = stmt.executeQuery(SQLQuery);
            while (rset.next()) {
                String body = rset.getString("body");
                textField.setText(body);
            }
/**
 * den skapar alternativerna och body samtidigt.
 *
 */
            String strSelect = "select description, target_id from links where story_id = " + currentRoom;
            storyLinks.removeAll(storyLinks);
            //int currentRoom = 1;
            rset = stmt.executeQuery(strSelect);

            rset.next();
            String description = rset.getString("description");
            val1.setText(description);
            int target_id = rset.getInt("target_id");
            storyLinks.add(target_id);

            rset.next();
            description = rset.getString("description");
            val2.setText(description);
            target_id = rset.getInt("target_id");
            storyLinks.add(target_id);
            conn.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tabel = new JPanel();
        tabel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabel.setBackground(new Color(-3023298));
        val1 = new JButton();
        val1.setText("");
        tabel.add(val1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        val2 = new JButton();
        val2.setText("");
        tabel.add(val2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField = new JTextField();
        tabel.add(textField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 1, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tabel;
    }

}